#!/bin/sh
test -e /tmp/dwmstatus && exit
trap "rm /tmp/dwmstatus" EXIT

while true
do
	xsetroot -name "$(cat /sys/class/power_supply/*/capacity) $(date "+%a %Y-%m-%d %H:%M") $(sein compacter)"
	sleep 30
done
