#!/bin/sh
test -e /tmp/dwmstatus && exit
touch /tmp/dwmstatus
trap "rm /tmp/dwmstatus" EXIT

while true
do
	xsetroot -name "$(cat /sys/class/power_supply/*/capacity) $(bein) $(date "+%a %Y-%m-%d %H:%M")"
	sleep 30
done
