#!/bin/sh

RESULT=$(mpc -f %albumartist%\\t%album% listall | uniq | dmenu)
ARTIST=$(echo "$RESULT" | sed -e 's/\t.*//')
ALBUM=$(echo "$RESULT" | sed -e 's/.*\t//')

mpc clear
test -n "$RESULT" && mpc search album "$ALBUM" albumartist "$ARTIST" | mpc add
mpc play
